In [1]:
import numpy as np
import pylab as plt
%matplotlib inline

In [129]:
class BM(object):
    def __init__(self, data):
        self.data = data
        self.n = data.shape[1]
        self.init_state()
        self.init_bios()
        self.init_weight()
        self.init_all_state()
    def init_state(self):
        self.s = np.matrix(np.zeros((self.n, 1)))
    def init_bios(self):
        self.b = np.matrix(np.zeros((self.n, 1)))
    def init_weight(self):
        self.w = np.matrix(np.zeros((self.n, self.n)))
    def init_all_state(self):
        n = self.n
        m = 2**n
        u = np.matrix(np.zeros((m, n)))
        for i in range(n-1, -1, -1):
            offset = 2**(n-i-1)
            for j in range(0, m, offset*2):
                u[j:j+offset,i] = 0
                u[j+offset:j+offset*2,i] = 1
        self.u = u
    def E(self):
        return - self.b.T * self.s - self.s.T * self.w * self.s
    def E_v(self, v):
        return - self.b.T * v - v.T * self.w * v
    def Z(self):
        s = 0
        m = 2**self.n
        for i in range(m):
            s += np.exp(-self.E_v(self.u[i,:].T))
        return s
    def P(self, v):
        return np.exp(-self.E_v(v)) / self.Z()

In [130]:
data = np.array([[1,1,0,0],[1,0,0,0],[0,1,0,0],[0,0,0,1]])

In [131]:
bm = BM(data)

In [132]:
bm.E()

matrix([[ 0.]])

In [139]:
bm.P(np.matrix([1,1,1,1]).T)

matrix([[ 0.0625]])

In [140]:
bm.Z()

matrix([[ 16.]])

In [141]:
bm.E_v(np.matrix([1,1,1,1]).T)

matrix([[ 0.]])